# Generated by Django 5.0.1 on 2024-01-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('round', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='players.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['tournament'], name='matches_mat_tournam_fe8d47_idx'), models.Index(fields=['date'], name='matches_mat_date_a3271e_idx'), models.Index(fields=['round'], name='matches_mat_round_a38707_idx'), models.Index(fields=['winner'], name='matches_mat_winner__6e527e_idx'), models.Index(fields=['loser'], name='matches_mat_loser_i_b30cd8_idx')],
            },
        ),
    ]
