# Generated by Django 5.0.1 on 2024-01-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='matches_mat_winner__6e527e_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='matches_mat_loser_i_b30cd8_idx',
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='players.player'),
        ),
    ]
