# Generated by Django 5.0.1 on 2024-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_match_id_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=20),
        ),
    ]
