# Generated by Django 5.0.1 on 2024-01-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_id_alter_match_match_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='match_atp',
        ),
    ]
