# Generated by Django 5.0.1 on 2024-01-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_rename_match_id_match_match_atp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
