# Generated by Django 5.0.1 on 2024-01-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_loser_match_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
