# Generated by Django 5.0.1 on 2024-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hand', models.CharField(max_length=1)),
                ('country', models.CharField(max_length=3)),
                ('birthdate', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='players_pla_name_f5b1bf_idx'), models.Index(fields=['country'], name='players_pla_country_d6c639_idx'), models.Index(fields=['birthdate'], name='players_pla_birthda_0f2f40_idx')],
            },
        ),
    ]
