# Generated by Django 5.0.1 on 2024-01-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_id_alter_player_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='player_atp',
        ),
    ]
